CREATE DATABASE IF NOT EXISTS ecomdb;
USE ecomdb;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	stock INT NOT NULL DEFAULT 0,
	categories VARCHAR(100) NOT NULL
);

CREATE TABLE cart(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,product_id INT,quantity INT);

CREATE TABLE order_items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	order_id INT NOT NULL DEFAULT 0,
	user_id INT NOT NULL DEFAULT 0,
	product_id INT NOT NULL,
	quantity INT NOT NULL DEFAULT 1,
	price DECIMAL(10,2) NOT NULL
);

CREATE TABLE customers (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL UNIQUE,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL,
	mobile VARCHAR(30) NOT NULL,
	address_line1 VARCHAR(255) NOT NULL,
	address_line2 VARCHAR(255) NOT NULL,
	country VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	state VARCHAR(100) NOT NULL,
	zip_code VARCHAR(20) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE orders (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	customer_id INT NOT NULL,
	total_amount DECIMAL(10,2) NOT NULL,
	status VARCHAR(30) NOT NULL DEFAULT 'Placed',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);